---
layout: cv
title: Josh Woods's CV
---
# Josh Woods

<div id="webaddress">
<a href="woodsjosh01.jw@gmail.com">woodsjosh01.jw@gmail.com</a>
</div>

# Joshua Woods

**Email:** woodsjosh01.jw@gmail.com • **Phone:** 254 278 1031 • [LinkedIn](linkedin.com/in/joshua woods2)

## Education
**Brigham Young University - Idaho**  
_Sep 2022 - Dec 2025_  
**Bachelor of Science; Computer Science**  
Overall GPA: 3.97 / 4.00

## Experience

**Brigham Young University - Web Development Tutor; Idaho**  
_April 2024 - Present_  

* Instruct students in HTML, CSS, and JavaScript, cultivating independent problem-solving abilities and practical application skills.
* Guide students through homework assignments, emphasizing conceptual understanding and skill development over direct completion.
* Mentored and assisted 13 students in a semester, contributing to proficiency and confidence in frontend web development.
* Facilitate interactive workshops and personalized sessions, resulting in measurable improvements in student performance and comprehension.

**Storm's Drive-In - Fast-Food Employee; Lampasas, TX**  
_September 2017 - May 2020_  

* Collaborated with team members to achieve optimal customer satisfaction.
* Managed various types of equipment and participated in workflow tasks as needed.
* Organized each shift to address and resolve arising issues.
* Trained new employees on operational procedures and customer service standards.

## Leadership, Activities, Honors

**Code Interview Society – Member; Rexburg, ID**  
_September 2023 - December 2023_  

* Competed in various coding challenges to apply and enhance relevant technical skills.
* Collaborated with teammates to problem-solve efficiently, reviewing and improving each other's code.
* Analyzed and discussed different algorithmic approaches to optimize coding solutions.

**The Church of Jesus Christ of Latter-day Saints – Full-time Missionary; Wisconsin Milwaukee Mission**  
_May 2020 - May 2022_  

* Committed 40+ hours per week to community service and outreach initiatives.
* Developed effective communication skills through interactions with diverse cultural and linguistic groups.
* Led and trained a team of 8 missionaries, facilitating professional development and goal-setting.
* Organized and led weekly community service projects, involving local residents and organizations.

## Additional Information

- **Skills:** Python, C#, JavaScript, HTML/CSS, GitHub, MySQL/PostgreSQL, R, Svelte, Express.js
- **Certifications:** Computer Programming, Full-Stack Web Development (In progress), Machine Learning (In progress)
- **Languages:** Working knowledge in Hmong
- **Work Eligibility:** Eligible to work in the U.S. with no restrictions

<!-- ### Footer

Last updated: May 2013 -->